### PR TITLE
Add homebrew drama

### PR DESCRIPTION
**Pull request by OptimusCrime**
@MikeMcQuaid bans everyone who :-1: his comments.

Source: https://www.reddit.com/r/programmingcirclejerk/comments/8200wl/senior_engineer_at_github_blocks_anyone_who_his/

### CODE REVIEW

**Comment by bfred-it** [comment]
Conversation is gone

**Comment by OptimusCrime** [comment]
Ah, come on. @nikolas is it okey to link to the cache provided by @bfred-it ?

**Comment by bfred-it** [comment]
No, bing's cache will be gone

**Comment by OptimusCrime** [comment]
Ẁhat about the image? Or is it possible to make archive.org archive the bing cache?

**Comment by OptimusCrime** [comment]
Edit: should be stored forever here https://web.archive.org/web/20180305121204/http://cc.bingj.com/cache.aspx?q=https%3a%2f%2fgithub.com%2fHomebrew%2fhomebrew-core%2fissues%2f24654&d=695653734807&mkt=en-WW&setlang=en-US&w=Pu9hVlBoNKrKONMP0ZEtZ0J600Qly9xB

**Comment by bfred-it** [comment]
The image should work forever

**Comment by nikolas** [comment]
hah - this is amazing. @MikeMcQuaid :P

**Pull request merged**
