### PR TITLE
add spacemacs CoC discussion

### PR DESCRIPTION
**Pull request by neeasade**

### CODE REVIEW

**Comment by philsturgeon** [comment]
So tempted to throw my https://philsturgeon.uk/2016/09/15/codes-of-conduct-maybe-theyre-not-so-bad/ in there but better not wake a sleeping bear. So many nerds freaking out about CoC. Lol

**Comment by bullno1** [comment]
@philsturgeon Please don't create a drama here. That would be too meta.

**Comment by philsturgeon** [comment]
I would never! 😇

**Comment by Sjneugent** [comment]
Well, emacs is the worst so good drama.  10/10 jerking.

**Pull request merged**
