### PR TITLE
New core-js drama: Denis Pushkarev (Zloirock, console spammer, Russian pedestrian homicider)

### PR DESCRIPTION
**Pull request by Lin2Jing4**
New core-js drama: Denis Pushkarev (Zloirock, console spammer, Russian pedestrian homicider)

Denis Pushkarev, known as Zloirock on GitHub, maintains the core-js library on millions of websites and constantly spams the console of the millions of developers who indirectly import core-js. Pushkarev is a Russian who served about ten months in prison in 2020 for colliding with two pedestrians on his motorcycle, killing one of them.

Pushkarev said he's ready to give up open-source development because few people pay for the software. Pushkarev posted a 70000-character, 10000-word screed and opened an issue on GitHub titled "So, what's next?" in February 2023.

Journalism:
https://www.theregister.com/2020/03/26/corejs_maintainer_jailed_code_release https://www.theregister.com/2023/02/15/corejs_russia_open_source

GitHub Issues:
https://github.com/zloirock/core-js/issues/548
https://github.com/zloirock/core-js/issues/635
https://github.com/zloirock/core-js/issues/767
https://github.com/zloirock/core-js/issues/1179
https://github.com/nikolas/github-drama/issues/153

Pushkarev's 10000-word screed:
https://github.com/zloirock/core-js/blob/master/docs/2023-02-14-so-whats-next.md

The archives of the web pages are available on the following Web services:
https://archive.today/
https://web.archive.org/
https://ghostarchive.org/

### CODE REVIEW

**Comment by ultracodez** [comment]
He does _NOT_ spam consoles. Why so heartless?

**Comment by jack9603301** [comment]
Because the quality is very low, there are two kinds of people with low quality, one is to use the author to insult the author and laugh at the author, the other is not to laugh at the author, but to start using donations to morally kidnap users.

**Comment by jack9603301** [comment]
Because the quality is very low, there are two kinds of people with low quality, one is to use the author to insult the author and laugh at the author, the other is not to laugh at the author, but to start using donations to morally kidnap users.

**Comment by jack9603301** [comment]
> He does _NOT_ spam consoles. Why so heartless?

Because the quality is very low, there are two kinds of people with low quality, one is to use the author to insult the author and laugh at the author, the other is not to laugh at the author, but to start using donations to morally kidnap users.

And these two kinds, I estimate to have the share of Chinese netizen, and the likelihood that hold a proportion is more main.

I am willing to communicate with the author, and make a summary and listen, may not be able to provide substantive help, the author's own community governance line is also wrong.

**Comment by polkovnikov-ph** [comment]
> He does NOT spam consoles. Why so heartless?

Not anymore, because `npm` disabled it. (And most likely `core-js` was one of the largest reasons behind it, because it spammed its messages in half of the frontend projects.)

"Spamming is the use of messaging systems to send multiple unsolicited messages", so this is spam by definition.

His linked article gives reasons behind it, and I find his reasoning legit. But emotions don't change facts.

**Comment by polkovnikov-ph** [comment]
@jack9603301 Please, consider using Google Translate. I used it on your previous messages in Chinese in that thread, and it produced high-quality English out of them.

**Comment by hinell** [comment]
I have to thumb this case up as it's remarkably politicized case given the ongoing Ukranian war and FOSS failure to get money/monetize their business.

**Pull request closed without merging**
