### PR TITLE
Golang porn training drama

### PR DESCRIPTION
**Pull request by kxepal**

### CODE REVIEW

**Comment by nikolas** [comment]
Thanks, but this thread isn't particularly dramatic. I think we can do better.

**Comment by kxepal** [comment]
Ok (: 
I think would be nice to see some CONTRIBUTING where drama requirements will be defined. This will help to sort out good ones from bad ones. Could you make the one?

**Comment by nikolas** [comment]
yeah, good idea.. i'll make that

**Comment by kxepal** [comment]
Thanks!

**Comment by nikolas** [comment]
Alright I made a contributing guideline document here: https://github.com/nikolas/github-drama/blob/master/CONTRIBUTING.md

I really just want to be careful and not make this repository a listing of every crazy github thread, since I'm sure there are many, but they're not always that funny. I think the more unique situations are funnier, like for example, a former mozilla employee making angry pull requests like this https://github.com/mozilla-jetpack/jpm/pull/357/commits

**Comment by kxepal** [comment]
@nikolas :+1:

**Pull request closed without merging**
