### PR TITLE
Added OpenCART drama

### PR DESCRIPTION
**Pull request by Plazmaz**
Old, but a good read. There's a lot more of these, but I picked three.
https://github.com/opencart/opencart/issues/3834
https://github.com/opencart/opencart/issues/1534
and
https://github.com/opencart/opencart/issues/1269

### CODE REVIEW

**Comment by OptimusCrime** [comment]
I can not see the first one?

**Comment by Plazmaz** [comment]
@OptimusCrime sorry, the archive link is in the commit.
https://web.archive.org/web/20160120051637/https://github.com/opencart/opencart/issues/3834

**Comment by OptimusCrime** [comment]
Ah, sorry. I did not see the actual commit. Nice!

**Comment by Daniel15** [comment]
You missed https://github.com/opencart/opencart/pull/1594... I wonder if it should be added too. 😛

**Pull request merged**
