### PR TITLE
Add 'I hate tensorflow' issue (much drama)

### PR DESCRIPTION
**Pull request by InCogNiTo124**
https://github.com/tensorflow/tensorflow/issues/53549

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
I don't think that is really drama but more spamming :) But I might be biased :P

**Comment by InCogNiTo124** [comment]
> I don't think that is really drama but more spamming :) But I might be biased :P

It had drama potential before it was locked, though :))

**Comment by branc116** [comment]
New drama: Drama on Github Drama - is `I Hate Tensorflow Drama` drama or is it not a drama?

**Comment by InCogNiTo124** [comment]
> New drama: Drama on Github Drama - is `I Hate Tensorflow Drama` drama or is it not a drama?

Meta

**Comment by nikolas** [comment]
Not dramatic enough but thx

**Pull request closed without merging**
