### PR TITLE
added spring rest hateoas discussion on the exposure of the id field

### PR DESCRIPTION
**Pull request by boeboe**

### CODE REVIEW

**Comment by philsturgeon** [comment]
No drama here, just a respectful discussion about how an opinionated framework does stuff. Opinions were shared, but that doesnt make it drama. 🤷‍♂️

**Comment by boeboe** [comment]
Well, I was hoping that it would qualify as drama, since a lot of folks had goid arguments and in the end they closed the thread leaving people to go design there own solution :)

**Comment by philsturgeon** [comment]
A lot of folks had ideas but they weren’t gold. Lots of folks saying a thing doesn’t validate the thing. 

--
Phil Sturgeon
@philsturgeon

**Comment by bullno1** [comment]
Yeah, we need name calling, reaction spam and meme pictures to qualify.

**Comment by nikolas** [comment]
lol i love it when people passive-aggressively react with the confused smiley.

**Pull request merged**
