### PR TITLE
add pfsense-closedsource repo

### PR DESCRIPTION
**Pull request by chris48s**
An entire repository of drama, or just forum drama rehashed on GitHub

### CODE REVIEW

**Comment by nallar** [comment]
That repo got DMCAd - does that count as even more drama? 

It's sort of resurrected as ["pfsense-still-closedsource"](https://github.com/doktornotor/pfsense-closedsource).

**Comment by OptimusCrime** [comment]
That other repo was DMCAd as well.

**Comment by vaindil** [comment]
No, the other repo is fine, @nallar linked to the wrong one. [doktornotor/pfsense-still/closedsource](https://github.com/doktornotor/pfsense-still/closedsource)

**Comment by OptimusCrime** [comment]
Ah, there we go. Nice.

**Pull request merged**
