### PR TITLE
Added fakerjs lastname drama

### PR DESCRIPTION
**Pull request by OAyomide**
Added the short albeit micro-aggressive last name drama on fakerjs

### CODE REVIEW

**Comment by nikolas** [comment]
Damn, this issue was deleted and I can't see it on archive.org either: https://web.archive.org/web/*/https://github.com/Marak/faker.js/issues/735

**Comment by OAyomide** [comment]
Lol.. that sucks

The 'discussion' was really quite tense/heated. It was political. The issue opener had personal issues with using the 'Gay' name to generate the lastnames.

How did they find out so fast? :laughing:

**Comment by philsturgeon** [comment]
It was not so much political, or a concern about the word "gay" (the word gay is no offensive to anyone). The concern was more likely to be down to "Gaylord" being used as an insult almost exclusively by 9 year olds. Nobody else uses that as an insult. I'm sure being lord of the gays isn't something that would offend many gay folks.

**Comment by OAyomide** [comment]
:+1:

**Comment by nikolas** [comment]
closing because issue is 404

**Pull request closed without merging**
