### PR TITLE
Added the link to notepad++ Chinese invasion

### PR DESCRIPTION
**Pull request by kasthack**
It's been flooded with sinobots and butthurt commies after condemning Chinese concentration camps for Uyghurs

### CODE REVIEW

**Comment by vaindil** [comment]
Just linking to the issue tracker is only good in the short term, I'm not sure what the best way is to archive this. It might be best to link the issues that have gotten replies (in the same format as other issue links), but that list could get long very quickly.

**Comment by kasthack** [comment]
I would probably add date filter to the query and add sorting by number of comments, somthing like this:

[is:issue created:2019-10-30 sort:comments-desc](https://github.com/notepad-plus-plus/notepad-plus-plus/issues?q=is%3Aissue+created%3A2019-10-30+sort%3Acomments-desc)

AFAIK, they are planning to clean up the issue tracker a bit but probably they'll keep some of them.

**Comment by redguardtoo** [comment]
It might be better not to merge this pull request. The root cause is the notepad++ author embedded some ideology thing into the application. So the whole thing is purely politics.
Unlike other drama, I can't learn anything from this "drama" as a developer.

I believe developer expected get latest tech related dramas.  If they were interested in anything like Trump, Brexit, Catalan conflicts ..., they would go elsewhere.

I don't want this wonderful site deteriorates into another  reddit news`

**Comment by kasthack** [comment]
ok

**Pull request closed without merging**
